[IOPAE-1398] Fetch vehicles
pagopa/io-ipatente pull request #11
Opened 2024-09-20 14:00 UTC by adelloste

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-20 20:56 UTC, gunzip reviewed
lacks unit tests

2024-09-20 20:56 UTC, gunzip commented on apps/my-vehicles/src/hooks/useVehicles.ts
> +    queryKey: ["vehicles"],
queryKey Should Include all dependencies, ie. `queryKey: ["vehicles", fiscalCode]`

2024-09-26 10:00 UTC, giuseppedipinto requested changes

2024-09-26 13:13 UTC, adelloste commented on apps/my-vehicles/src/hooks/useVehicles.ts
> +const fetchVehicles = async (fiscalCode: string) => {
Removed `fiscalCode` from bff openapi and updated `fetchVehicles`

2024-09-26 13:18 UTC, adelloste commented on apps/my-vehicles/package.json
> +    "@tanstack/react-query-devtools": "^5.56.2",
according to the doc, we can add @tanstack/react-query-devtools as a dependency

2024-09-26 13:25 UTC, giuseppedipinto approved these changes
LGTM

2024-09-26 13:34 UTC, merged