[IOPAE-1601] mock receipt download
pagopa/io-ipatente pull request #157
Opened 2024-12-03 13:37 UTC by loricurreli

#### List of Changes

Add the download function in the payment detail section

#### Motivation and Context

We need to download the file containing the payment's receipt

#### How Has This Been Tested?

There is a dedicated test for the new api /api/pagamenti/ricevuta/:id

#### Screenshots (if appropriate):

![Simulator Screenshot - iPhone 15 Pro - 2024-12-03 at 14 35 28](https://github.com/user-attachments/assets/6852eeda-4d10-47a9-a301-0d9b49080aa9)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-12-03 14:40 UTC, adelloste requested changes

2024-12-03 14:40 UTC, adelloste commented on packages/ui/lib/components/icon/Icon.tsx
> +import Download from "./svg/Download";
```suggestion
import IconDownload from "./svg/Download";
```

2024-12-03 14:40 UTC, adelloste commented on packages/core/lib/wrappers/with-jwt-auth-handler.ts
> +      params: ctx.params,
```suggestion
      ...ctx,
```

2024-12-04 08:17 UTC, giuseppedipinto requested changes
I left a couple of comments that are meant to be some food for thought before merge

2024-12-04 08:17 UTC, giuseppedipinto commented on apps/payments/src/lib/bff/business.ts
> +      headers: {
we are forgetting `codiceFiscale` as header: it's required in all apis

2024-12-04 08:17 UTC, giuseppedipinto commented on apps/payments/src/pages/payments/[requestId].tsx
> +          <Button
let's check if the button should be displayed only under certain conditions _(example: particular practice status, even if we know that the practice status is not an enumeration...)_

2024-12-05 16:11 UTC, adelloste approved these changes

2024-12-05 21:20 UTC, giuseppedipinto approved these changes

2024-12-06 09:48 UTC, merged